### ISSUE TITLE
How to include more than one parser in a program?

### ISSUE THREAD

**Issue by fletcher** [fasterthanlime/greg#20]
I am creating a quick and dirty test program around my parser built with `greg`.  In order to parse the test files, it's easiest to do by building another parser.

Since both parsers are built with `greg`, there are namespace collisions:

    duplicate symbol _yyparse_from in:
        test.o
        parser.o
    duplicate symbol _yyparse in:
        test.o
        parser.o
    duplicate symbol _yyinit in:
        test.o
        parser.o
    duplicate symbol _yydeinit in:
        test.o
        parser.o
    duplicate symbol _yyparse_new in:
        test.o
        parser.o
    duplicate symbol _yyparse_free in:
        test.o
        parser.o

Any tips on how to make this work?  Surely it is possible to use more than one parser in a given program?

Any advice is appreciated!!

**Comment by fletcher** [comment]
And of course, after hitting send I discovered the YY_NAME macro....

Thanks, and sorry for posting this 30 seconds too soon!

**Comment by nddrylliog** [comment]
No problem, glad you could find what you were looking for :)
